### ISSUE TITLE
Swipe 组件的 mt-swipe-item能否用 v-for 循环渲染？

### ISSUE THREAD

**Issue by starsea** [ElemeFE/mint-ui#122]
因为 swipe 的内容是从 api 获取的 所以想问下是否有这种功能？

**Comment by Leopoldthecoder** [comment]
可以。

**Comment by longyunrui** [comment]
可以是可以，但是会报错
client?2142:153 ./node_modules/_vue-loader@13.7.2@vue-loader/lib/template-compiler?{"id":"data-v-7df7329a","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/_vue-loader@13.7.2@vue-loader/lib/selector.js?type=template&index=0!./src/layouts/MyQrCodeLayout/MyQrCodeLayout.vue
(Emitted value instead of an instance of Error) <mt-swipe-item v-for="walletInfo in walletsDataInfo">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./src/layouts/MyQrCodeLayout/MyQrCodeLayout.vue 12:0-414
 @ ./src/layouts/MyQrCodeLayout/index.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://192.168.16.113:8080 webpack/hot/dev-server ./src/main.js
